#x =0

def Function(x):
    return x

print(Function(2))

try:
    print(x)
except Exception as e:
    print(e)
