# EXCEPTION CASE 29_1
try:
    x = 4
except:
    print("exception")
else:
    raise
    print("no exception found")
finally:
    raise
    print("final output")

print(4)
