# EXCEPTION CASE 29
try:
    x=4
except:
    print("exception")
else:
    print("no exception found")
finally:
    raise
    print("final output")

print(4)
